- id: terraform-vars
  name: terraform-unused-vars
  description: Find unused variables in Terraform.
  language: python_venv
  files: (\.tf)$
  exclude: \.terraform\/.*$
  minimum_pre_commit_version: 1.9.0
  entry: terraform-unused-vars --quiet
